### ISSUE TITLE
退出游戏

### ISSUE THREAD

**Issue by Seayay** [LemonNeko2452/WolfKill#2]
貌似没有退出功能？（

**Comment by LemonNeko2452** [comment]
没有单人退出游戏的 可以game-stop结束整局游戏


------------------

Lemon&nbsp;Neko
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Aug 30, 2022 8:10 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[LemonNeko2452/WolfKill] 退出游戏 (Issue #2)





 
貌似没有退出功能？（

**Comment by LemonNeko2452** [comment]
等我闲下来再加功能吧，我现在忙着课设

**Comment by LemonNeko2452** [comment]
添加了
