### ISSUE TITLE
开始一场游戏后直接报胜利者？？

### ISSUE THREAD

**Issue by haorwen** [LemonNeko2452/WolfKill#5]
如题，无论是自定义还是标准
![image](https://user-images.githubusercontent.com/62163341/196036338-045d0dfa-58ec-4766-84f8-7af8b45a402c.png)

**Comment by haorwen** [comment]
且后台无报错

**Comment by haorwen** [comment]
![image](https://user-images.githubusercontent.com/62163341/196037470-24ce21fa-9521-40bf-9fb6-9e427cec7d53.png)
感觉这个文件怪怪的（？

**Comment by LemonNeko2452** [comment]
这是记录游戏进程的数据文件
看一下goods里面有没有数据

**Comment by haorwen** [comment]
![image](https://user-images.githubusercontent.com/62163341/196037605-3b14c2cf-65c0-4145-931a-b11a44101475.png)

**Comment by LemonNeko2452** [comment]
解决了

**Comment by haorwen** [comment]
芜湖，感谢
